### PR TITLE
Change site font to Lato - Do not merge until Ben approves

### PR DESCRIPTION
**Pull request by brkane**
The main Growhous website uses Lato as it's font. Use it here for
consistency.

### CODE REVIEW

**Comment by brkane** [comment]
I had to pull require statements out of application.scss to get the bootstrap mixin to work, which includes your datatable reference, we need to use @import to pull it in.

**Comment by brkane** [comment]
Should be good now. Please review and merge

**Comment by bjmllr** [comment]
:+1:

**Comment by brkane** [comment]
This should resolve #39

**Pull request merged**
